use_frameworks!

platform :ios, '9.0'

target 'FYFJSInvokePlugins_Example' do
  pod 'FYFJSInvokePlugins', :path => '../'
  pod 'FYFWebComponent', :git => 'https://github.com/fanyunfei786452470/FYFWebComponent.git'
  pod 'FYFCategory', :git => 'https://github.com/fanyunfei786452470/FYFCategory.git'
  pod 'FYFDefines', :git => 'https://github.com/fanyunfei786452470/FYFDefines.git'
  pod 'FYFDeviceInfo', :git => 'https://github.com/fanyunfei786452470/FYFDeviceInfo.git'
  
  target 'FYFJSInvokePlugins_Tests' do
    inherit! :search_paths

    
  end
end
