
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'FYFJSInvokePlugins_Example' do
  pod 'FYFJSInvokePlugins', :path => '../'
  pod 'FYFWebComponent'
  
  target 'FYFJSInvokePlugins_Tests' do
    inherit! :search_paths

    
  end
end
